'use client'

import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'

// ── SVG icon components ──────────────────────────────────────────────────────

function IconTarget() {
  return (
    <svg className="w-7 h-7 text-white" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="6" />
      <circle cx="12" cy="12" r="2" />
    </svg>
  )
}

function IconLightning() {
  return (
    <svg className="w-7 h-7 text-white" fill="currentColor" viewBox="0 0 24 24">
      <path d="M13 2 4.5 13.5H11L10 22 20.5 10.5H14L13 2Z" />
    </svg>
  )
}

function IconTrophy() {
  return (
    <svg className="w-7 h-7 text-white" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M6 9H4.5a2.5 2.5 0 010-5H6m12 5h1.5a2.5 2.5 0 000-5H18m-12 5v4a6 6 0 0012 0V9M9 21h6m-3-3v3" />
    </svg>
  )
}

function IconPeople() {
  return (
    <svg className="w-7 h-7 text-white" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857m0 0a5.002 5.002 0 00-9.288 0M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857M15 7a3 3 0 11-6 0 3 3 0 016 0z" />
    </svg>
  )
}

function IconTrending() {
  return (
    <svg className="w-7 h-7 text-white" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" d="M13 7h8m0 0v8m0-8-8 8-4-4-6 6" />
    </svg>
  )
}

function IconCalendar() {
  return (
    <svg className="w-7 h-7 text-white" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
      <rect x="3" y="4" width="18" height="18" rx="2" />
      <line x1="16" y1="2" x2="16" y2="6" />
      <line x1="8" y1="2" x2="8" y2="6" />
      <line x1="3" y1="10" x2="21" y2="10" />
    </svg>
  )
}

function IconStar() {
  return (
    <svg className="w-5 h-5 text-white" fill="currentColor" viewBox="0 0 24 24">
      <path d="M12 2l2.4 7.4H22l-6.2 4.5 2.4 7.4L12 17l-6.2 4.3 2.4-7.4L2 9.4h7.6L12 2z" />
    </svg>
  )
}

// ── Data ──────────────────────────────────────────────────────────────────────

const features = [
  {
    Icon: IconTarget,
    gradient: 'from-blue-500 to-indigo-600',
    title: 'AI-Generated Roadmaps',
    description: 'Personalized learning paths tailored to your goals and current skill level',
    href: '/roadmap/search',
  },
  {
    Icon: IconLightning,
    gradient: 'from-violet-500 to-purple-700',
    title: 'Micro-Learning Tasks',
    description: 'Break down complex skills into simple daily tasks you can actually complete',
    href: '/dashboard',
  },
  {
    Icon: IconTrophy,
    gradient: 'from-amber-400 to-orange-500',
    title: 'Gamified Rewards',
    description: 'Earn coins and badges as you progress through your learning journey',
    href: '/gamification/badges',
  },
  {
    Icon: IconPeople,
    gradient: 'from-emerald-400 to-green-600',
    title: 'Learner Community',
    description: 'Join an exclusive community to ask questions and share knowledge',
    href: '/community/feed',
  },
  {
    Icon: IconTrending,
    gradient: 'from-pink-500 to-rose-600',
    title: 'Progress Tracking',
    description: 'Visual dashboards to monitor your advancement and stay motivated',
    href: '/dashboard',
  },
  {
    Icon: IconCalendar,
    gradient: 'from-violet-500 to-indigo-600',
    title: 'Expert Sessions',
    description: 'Book 30-minute sessions with industry experts using your earned coins',
    href: '/expert',
  },
]

const stats = [
  { value: 50, suffix: 'K+', label: 'Active Learners' },
  { value: 1000, suffix: '+', label: 'Skill Paths' },
  { value: 95, suffix: '%', label: 'Success Rate' },
  { value: 200, suffix: '+', label: 'Expert Mentors' },
]

const steps = [
  {
    num: '01',
    gradient: 'from-indigo-500 to-violet-600',
    title: 'Create Your Profile',
    desc: 'Tell us your goals, current skills, and learning preferences to personalise your experience.',
  },
  {
    num: '02',
    gradient: 'from-violet-500 to-purple-600',
    title: 'Get Your AI Roadmap',
    desc: 'Receive a step-by-step learning path generated by our AI, tailored just for you.',
  },
  {
    num: '03',
    gradient: 'from-pink-500 to-rose-600',
    title: 'Learn & Earn Rewards',
    desc: 'Complete tasks, earn coins and badges, and track your journey toward mastery.',
  },
]

// ── Animated stat card ────────────────────────────────────────────────────────

function StatCard({
  value,
  suffix,
  label,
  triggered,
}: {
  value: number
  suffix: string
  label: string
  triggered: boolean
}) {
  const [count, setCount] = useState(0)

  useEffect(() => {
    if (!triggered) return
    const duration = 1800
    const start = Date.now()
    const timer = setInterval(() => {
      const progress = Math.min((Date.now() - start) / duration, 1)
      const eased = 1 - Math.pow(1 - progress, 3)
      setCount(Math.floor(eased * value))
      if (progress >= 1) clearInterval(timer)
    }, 16)
    return () => clearInterval(timer)
  }, [triggered, value])

  return (
    <div className="stat-card bg-white rounded-2xl p-6 text-center shadow-sm border border-gray-100 group cursor-default select-none">
      <div className="text-3xl sm:text-4xl font-extrabold text-gray-900 mb-2 group-hover:text-indigo-600 transition-colors duration-300">
        {count}
        {suffix}
      </div>
      <div className="text-sm text-gray-500 font-medium">{label}</div>
    </div>
  )
}

// ── Rotating text word ───────────────────────────────────────────────────────

function RotatingText({ words }: { words: string[] }) {
  const [idx, setIdx] = useState(0)
  const [phase, setPhase] = useState<'in' | 'out'>('in')

  useEffect(() => {
    const cycle = setInterval(() => {
      setPhase('out')
      setTimeout(() => {
        setIdx((i) => (i + 1) % words.length)
        setPhase('in')
      }, 300)
    }, 2800)
    return () => clearInterval(cycle)
  }, [words.length])

  return (
    <span
      className="inline-block font-semibold text-indigo-600"
      style={{
        opacity: phase === 'in' ? 1 : 0,
        transform: phase === 'in' ? 'translateY(0)' : 'translateY(-8px)',
        transition:
          phase === 'in'
            ? 'opacity 0.32s ease-out, transform 0.32s ease-out'
            : 'opacity 0.24s ease-in, transform 0.24s ease-in',
      }}
    >
      {words[idx]}
    </span>
  )
}

// ── Data: rotating skills + skill tag pills ───────────────────────────────────

const rotatingSkills = ['Python', 'AI & Machine Learning', 'Web Development', 'Data Science', 'Cloud & DevOps']

const skillTags = [
  { emoji: '🐍', label: 'Python' },
  { emoji: '🤖', label: 'AI / ML' },
  { emoji: '📊', label: 'Data Science' },
  { emoji: '🌐', label: 'Web Dev' },
  { emoji: '📱', label: 'Mobile Dev' },
  { emoji: '☁️', label: 'Cloud' },
]

// ── Main component ────────────────────────────────────────────────────────────

export default function LandingClient() {
  const [statsVisible, setStatsVisible] = useState(false)
  const statsRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const scrollObs = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) e.target.classList.add('in-view')
        })
      },
      { threshold: 0.12 },
    )

    const statsObs = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting) {
          setStatsVisible(true)
          statsObs.disconnect()
        }
      },
      { threshold: 0.2 },
    )

    document.querySelectorAll('.animate-on-scroll').forEach((el) => scrollObs.observe(el))
    if (statsRef.current) statsObs.observe(statsRef.current)

    return () => {
      scrollObs.disconnect()
      statsObs.disconnect()
    }
  }, [])

  return (
    <div className="min-h-screen bg-white flex flex-col">
      {/* ── Navbar ── */}
      <nav className="bg-white/80 backdrop-blur-md border-b border-gray-100 px-6 py-3 flex items-center justify-between sticky top-0 z-50 shadow-sm">
        <div className="flex items-center gap-2.5">
          <div className="w-9 h-9 bg-linear-to-br from-indigo-600 to-violet-600 rounded-xl flex items-center justify-center shadow-md shadow-indigo-200">
            <IconStar />
          </div>
          <span className="text-xl font-bold text-gray-900 tracking-tight">SkillForge</span>
        </div>
        <div className="flex items-center gap-3">
          <Link
            href="/login"
            className="text-sm text-gray-600 hover:text-indigo-600 px-3 py-1.5 transition-colors font-medium"
          >
            Sign in
          </Link>
          <Link
            href="/register"
            className="text-sm bg-linear-to-r from-indigo-600 to-violet-600 text-white px-5 py-2 rounded-full hover:opacity-90 hover:scale-105 transition-all duration-200 font-semibold shadow-md shadow-indigo-200"
          >
            Get Started
          </Link>
        </div>
      </nav>

      {/* ── Hero ── */}
      <section className="relative overflow-hidden bg-linear-to-b from-indigo-50/60 via-white to-white px-6 py-24 sm:py-36 flex flex-col items-center text-center">

        {/* Dot grid background */}
        <div
          className="absolute inset-0 pointer-events-none"
          style={{
            backgroundImage: 'radial-gradient(rgba(99,102,241,0.09) 1px, transparent 1px)',
            backgroundSize: '28px 28px',
          }}
        />

        {/* Large blur orbs */}
        <div className="absolute top-10 left-1/4 w-80 h-80 bg-indigo-300/20 rounded-full blur-3xl animate-float-orb pointer-events-none" />
        <div className="absolute bottom-6 right-1/4 w-96 h-96 bg-violet-300/20 rounded-full blur-3xl animate-float-orb-2 pointer-events-none" />
        <div className="absolute top-1/3 right-[20%] w-56 h-56 bg-pink-300/15 rounded-full blur-2xl animate-float-orb-3 pointer-events-none" />

        {/* Sparkle dots */}
        <div className="absolute top-[22%] left-[13%] w-2.5 h-2.5 rounded-full bg-indigo-400/60 sparkle-dot pointer-events-none" />
        <div className="absolute top-[38%] left-[19%] w-1.5 h-1.5 rounded-full bg-violet-400/50 sparkle-dot-2 pointer-events-none" />
        <div className="absolute top-[17%] right-[15%] w-2 h-2 rounded-full bg-pink-400/55 sparkle-dot-3 pointer-events-none" />
        <div className="absolute top-[58%] right-[11%] w-1.5 h-1.5 rounded-full bg-indigo-400/45 sparkle-dot-4 pointer-events-none" />
        <div className="absolute top-[72%] left-[11%] w-2 h-2 rounded-full bg-violet-300/55 sparkle-dot-5 pointer-events-none" />

        {/* ── Center content ── */}

        {/* Badge */}
        <div className="badge-pop inline-flex items-center gap-2 bg-white border border-indigo-100 rounded-full px-4 py-1.5 mb-8 shadow-sm relative z-10">
          <svg className="w-4 h-4 text-indigo-500" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
          </svg>
          <span className="text-sm font-semibold text-indigo-600">AI-Powered Learning Platform</span>
        </div>

        {/* Headline */}
        <h1 className="hero-in-1 text-5xl sm:text-7xl font-extrabold leading-[1.08] tracking-tight mb-5 max-w-4xl relative z-10">
          <span className="bg-linear-to-r from-indigo-600 via-violet-600 to-indigo-600 bg-clip-text text-transparent animate-gradient-text">
            Transform Your Skills,
          </span>
          <br />
          <span className="text-gray-900">Forge Your Future</span>
        </h1>

        {/* Live rotating skill line */}
        <div className="hero-in-2 flex items-center justify-center gap-2 text-sm text-gray-500 mb-4 relative z-10">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse flex-shrink-0" />
          <span>
            Students mastering{' '}
            <RotatingText words={rotatingSkills} />
            {' '}right now
          </span>
        </div>

        {/* Subtitle */}
        <p className="hero-in-2 text-lg sm:text-xl text-gray-500 max-w-2xl mb-10 leading-relaxed relative z-10">
          A gamified educational platform designed to inspire continuous learning
          and guide you toward optimal knowledge pathways.
        </p>

        {/* CTAs */}
        <div className="hero-in-3 flex flex-col sm:flex-row items-center gap-4 mb-8 relative z-10">
          <Link
            href="/register"
            className="flex items-center gap-2 bg-linear-to-r from-indigo-600 to-violet-600 text-white px-8 py-4 rounded-full text-base font-semibold hover:opacity-90 hover:scale-105 active:scale-100 transition-all duration-200 shadow-lg shadow-indigo-200"
          >
            Start Learning Free
            <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth={2.5} viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
            </svg>
          </Link>
          <button className="flex items-center gap-2 border border-gray-200 bg-white text-gray-700 px-8 py-4 rounded-full text-base font-semibold hover:border-indigo-300 hover:text-indigo-600 hover:scale-105 active:scale-100 transition-all duration-200 shadow-sm">
            <svg className="w-5 h-5 text-indigo-400" fill="currentColor" viewBox="0 0 24 24">
              <path d="M8 5v14l11-7z" />
            </svg>
            Watch Demo
          </button>
        </div>

        {/* Skill tag pills */}
        <div className="hero-in-4 flex flex-wrap justify-center gap-2 mb-8 relative z-10 max-w-lg">
          {skillTags.map((tag, i) => (
            <span
              key={i}
              className="inline-flex items-center gap-1.5 bg-white border border-gray-100 text-gray-600 text-xs font-medium px-3 py-1.5 rounded-full shadow-sm hover:border-indigo-200 hover:text-indigo-600 transition-colors duration-200 cursor-default select-none"
              style={{ animation: `hero-in 0.5s ease-out ${0.85 + i * 0.07}s both` }}
            >
              {tag.emoji} {tag.label}
            </span>
          ))}
        </div>

        {/* Social proof */}
        <div className="hero-in-4 flex items-center gap-3 text-sm text-gray-400 relative z-10">
          <div className="flex -space-x-2">
            {['bg-indigo-400', 'bg-violet-400', 'bg-pink-400', 'bg-blue-400'].map((c, i) => (
              <div key={i} className={`w-7 h-7 rounded-full ${c} border-2 border-white`} />
            ))}
          </div>
          <span>
            <strong className="text-gray-600">50K+</strong> learners already on their journey
          </span>
        </div>
      </section>

      {/* ── Stats ── */}
      <section className="bg-[#f8f9fa] px-6 py-16">
        <div
          ref={statsRef}
          className="max-w-5xl mx-auto grid grid-cols-2 sm:grid-cols-4 gap-4 sm:gap-6"
        >
          {stats.map((s, i) => (
            <div
              key={i}
              className="animate-on-scroll"
              style={{ transitionDelay: `${i * 100}ms` }}
            >
              <StatCard {...s} triggered={statsVisible} />
            </div>
          ))}
        </div>
      </section>

      {/* ── Why SkillForge ── */}
      <section className="bg-white px-6 py-20 sm:py-28">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-14 animate-on-scroll">
            <h2 className="text-3xl sm:text-4xl font-extrabold text-gray-900 mb-4">
              Why SkillForge?
            </h2>
            <p className="text-gray-500 text-lg">Everything you need to master any skill</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {features.map((feat, i) => {
              const FeatureIcon = feat.Icon
              return (
                <Link
                  key={i}
                  href={feat.href}
                  className="feature-card animate-on-scroll bg-white border border-gray-100 rounded-2xl p-7 group block"
                  style={{ transitionDelay: `${(i % 2) * 120}ms` }}
                >
                  <div
                    className={`feat-icon w-14 h-14 rounded-2xl bg-linear-to-br ${feat.gradient} flex items-center justify-center mb-5 shadow-md`}
                  >
                    <FeatureIcon />
                  </div>
                  <div className="flex items-start justify-between gap-2">
                    <div>
                      <h3 className="text-lg font-bold text-gray-900 mb-2 group-hover:text-indigo-600 transition-colors duration-200">
                        {feat.title}
                      </h3>
                      <p className="text-gray-500 leading-relaxed text-sm">{feat.description}</p>
                    </div>
                    <svg
                      className="w-5 h-5 text-gray-300 group-hover:text-indigo-500 group-hover:translate-x-1 transition-all duration-200 shrink-0 mt-1"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth={2}
                      viewBox="0 0 24 24"
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                    </svg>
                  </div>
                </Link>
              )
            })}
          </div>
        </div>
      </section>

      {/* ── How it works ── */}
      <section className="bg-[#f8f9fa] px-6 py-20 sm:py-28">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-14 animate-on-scroll">
            <h2 className="text-3xl sm:text-4xl font-extrabold text-gray-900 mb-4">How It Works</h2>
            <p className="text-gray-500 text-lg">Three simple steps to start your learning journey</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-8 relative">
            {/* connector line (desktop) */}
            <div className="hidden sm:block absolute top-8 left-[16.67%] right-[16.67%] h-px bg-linear-to-r from-indigo-200 via-violet-200 to-pink-200 pointer-events-none" />

            {steps.map((step, i) => (
              <div
                key={i}
                className="step-card animate-on-scroll bg-white border border-gray-100 rounded-2xl p-8 text-center cursor-default"
                style={{ transitionDelay: `${i * 160}ms` }}
              >
                <div
                  className={`step-num w-16 h-16 rounded-2xl bg-linear-to-br ${step.gradient} flex items-center justify-center text-white text-xl font-extrabold mx-auto mb-5 shadow-md`}
                >
                  {step.num}
                </div>
                <h3 className="text-lg font-bold text-gray-900 mb-2">{step.title}</h3>
                <p className="text-gray-500 text-sm leading-relaxed">{step.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA banner ── */}
      <section className="relative overflow-hidden bg-linear-to-br from-indigo-600 via-violet-600 to-violet-700 px-6 py-24 text-center">
        <div className="absolute inset-0 opacity-10 pointer-events-none">
          <div className="absolute top-0 left-1/4 w-80 h-80 bg-white rounded-full blur-3xl" />
          <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-white rounded-full blur-3xl" />
        </div>
        <div className="relative z-10 max-w-2xl mx-auto animate-on-scroll">
          <h2 className="text-3xl sm:text-5xl font-extrabold text-white mb-5 leading-tight">
            Ready to forge your future?
          </h2>
          <p className="text-indigo-200 text-lg mb-10 leading-relaxed">
            Join thousands of learners already mastering new skills with AI-powered guidance.
          </p>
          <Link
            href="/register"
            className="inline-flex items-center gap-2 bg-white text-indigo-700 px-10 py-4 rounded-full text-base font-bold hover:bg-indigo-50 hover:scale-105 active:scale-100 transition-all duration-200 shadow-xl"
          >
            Get Started Free
            <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth={2.5} viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
            </svg>
          </Link>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer className="bg-gray-900 text-gray-400 px-6 py-10">
        <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 bg-linear-to-br from-indigo-500 to-violet-600 rounded-lg flex items-center justify-center">
              <IconStar />
            </div>
            <span className="text-white font-semibold">SkillForge</span>
          </div>
          <p className="text-sm">© 2026 SkillForge. Designed for learners.</p>
          <div className="flex gap-5 text-sm">
            <Link href="/login" className="hover:text-white transition-colors">
              Sign In
            </Link>
            <Link href="/register" className="hover:text-white transition-colors">
              Register
            </Link>
          </div>
        </div>
      </footer>

      {/* Help FAB */}
      <button
        aria-label="Help"
        className="fixed bottom-6 right-6 w-11 h-11 bg-indigo-600 text-white rounded-full flex items-center justify-center text-sm font-bold hover:bg-indigo-700 hover:scale-110 active:scale-100 transition-all duration-200 shadow-lg shadow-indigo-300 z-50"
      >
        ?
      </button>
    </div>
  )
}
